# Generated by Django 3.2.18 on 2023-05-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230521_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_genre',
        ),
    ]
