# Generated by Django 3.2.18 on 2023-04-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20230405_0820'),
        ('comments', '0002_initial'),
    ]

    operations = [
    ]
