# Generated by Django 3.2.18 on 2023-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.TextField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
