# Generated by Django 3.2.18 on 2023-04-02 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0002_auto_20230401_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='profile',
        ),
        migrations.AddField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
