# Generated by Django 3.2.18 on 2023-04-02 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_rename_image_movie_poster'),
        ('ratings', '0003_auto_20230402_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'movie')},
        ),
    ]
