# Generated by Django 3.2.18 on 2023-04-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20230402_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
