# Generated by Django 3.2.18 on 2023-04-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review',
            new_name='content',
        ),
    ]
