# Generated by Django 3.2.18 on 2023-05-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
    ]
