# Generated by Django 3.2.18 on 2023-05-26 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
        ('reports', '0003_auto_20230526_0813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('owner', 'movie')},
        ),
    ]
