# Generated by Django 3.2.18 on 2023-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('historical', 'Historical'), ('musical', 'Musical')], max_length=20),
        ),
    ]
