# Generated by Django 3.2.18 on 2023-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_rename_name_crew_crew_name'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movie_director', to='crew.Crew'),
        ),
    ]
