# Generated by Django 3.2.18 on 2023-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_auto_20230401_1419'),
        ('movies', '0002_alter_movie_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movie_director', to='crew.Director'),
        ),
    ]
