# Generated by Django 3.2.18 on 2023-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_auto_20230401_1419'),
        ('movies', '0004_rename_image_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movie_director', to='crew.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_cast',
            field=models.ManyToManyField(blank=True, related_name='movie_cast', to='crew.Actor'),
        ),
    ]
