# Generated by Django 3.2.18 on 2023-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20230402_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_cast',
            field=models.TextField(max_length=200),
        ),
    ]
